Use tempest-testing in misk-aws-dynamodb-testing
cashapp/misk pull request #1949
Opened 2021-05-31 22:18 UTC by zhxnlai

As documented here https://cashapp.github.io/tempest/guide/testing/

2021-05-31 22:25 UTC, zhxnlai commented on misk-aws-dynamodb-testing/src/main/kotlin/misk/aws/dynamodb/testing/DockerDynamoDbModule.kt
> +    install(ServiceModule<TestDynamoDb>())
this creates and cleans up tests tables

2021-05-31 22:33 UTC, chris-ryan-square requested changes
Needs updates to wisp aws2 dynamodb testing as well.

2021-05-31 23:05 UTC, chris-ryan-square commented on misk-aws-dynamodb-testing/src/main/kotlin/misk/aws/dynamodb/testing/DockerDynamoDbModule.kt
> +    install(ServiceModule<TestDynamoDb>())
💯

2021-05-31 23:05 UTC, chris-ryan-square approved these changes

2021-05-31 23:06 UTC, merged

2021-06-01 16:02 UTC, swankjesse commented
I’m seeing breaks in downstream projects like this:
```
    1) [Guice/ErrorInCustomProvider]: IllegalArgumentException: `dynamoDb` is only usable while the service is running
      at InProcessDynamoDbModule.providesAmazonDynamoDB(InProcessDynamoDbModule.kt:53)
          \_ installed by: MiskTestExtension$beforeEach$module$1 -> CashFaceTestingModule -> InProcessDynamoDbModule
```

2021-06-01 17:32 UTC, swankjesse commented
Some of the fixes to address that fallout:
 https://github.com/cashapp/backfila/pull/190
 https://github.com/squareup/cash-plasma/pull/2256