[WIP] Add histogram metric type
cashapp/misk pull request #2141
Opened 2021-09-14 16:50 UTC by MatthewDolan

Adds the ability to expose a prometheus histogram using misk metrics.

Replaces the `Metrics.histogram(...)` method (which as confusingly named because it actually created a prometheus `Summary` with two methods:
- `Metrics.summary(...)` which creates a prometheus `Summary`
- `Metrics.distribution(...)` which creates a prometheus `Histogram` (It isn't possible to update `Metrics.histogram(...)` to emit a histogram because that change would be backward-incompatible.)

2021-09-14 23:17 UTC, r3mariano commented on misk-metrics-testing/src/main/kotlin/misk/metrics/FakeMetrics.kt
> +  fun summaryQuantile(
You'll have to keep both for now so downstream services don't break

2021-09-15 00:16 UTC, cpakman requested changes
I think we don't need to force anyone to change - histogram and summary both append slightly different names to metrics:

histogram:
```
<name>_bucket
<name>_sum
<name>_count
```

summary:
```
<name>  (has quantiles)
<name>_sum
<name>_count
```

assuming prometheus library doesn't complain, we actually have no issues here if we just double write - _sum and _count should be identical between the two, and for signalfx it should be easy enough to write a drop rule to ignore <name>_bucket metrics. This way no code changes are necessary for consumers to get the advantages of either metric (though mostly likely if people have access to histogram, that'll be the better choice)

2021-09-15 14:38 UTC, MatthewDolan commented
Thanks for the feedback, @cpakman.

> histogram and summary both append slightly different names to metrics

I think what you are suggesting is similar to the issue I linked to and quoted in the description above (https://github.com/OpenObservability/OpenMetrics/issues/120).

(I know it's a little confusing that this issue isn't on the prometheus client directly, but instead on open metrics, but it references the prometheus client library which is how I found it. I could potentially submit a follow up issue to the prometheus client library.)

> assuming prometheus library doesn't complain

This is the sticking point. If I am reading the library code and the issue correctly, prometheus library will complain because of the way that it keeps metrics registered in a single map so it's not really feasible to register two metrics into a single name.

Additionally, there is a protocol problem even if we could patch or replace the client to accept both types under the same name.

The prometheus protocol explicitly defines the type for a given metric name in the scrape response. For example, section of the scrape response from one of our test services.

```
# HELP client_http_request_latency_ms count and duration in ms of outgoing client requests
# TYPE client_http_request_latency_ms summary
client_http_request_latency_ms{...,quantile="0.5",} 76.0
client_http_request_latency_ms{...,quantile="0.75",} 76.0
client_http_request_latency_ms{...,quantile="0.95",} 77.0
client_http_request_latency_ms{...,quantile="0.99",} 79.0
client_http_request_latency_ms{...,quantile="0.999",} 88.0
client_http_request_latency_ms_count{...,code="200",} 12872.0
client_http_request_latency_ms_sum{...,code="200",} 964256.0
```

Note that even though the metrics wouldn't collide like you suggest, it's not clear what `#TYPE` should be associated with this new hybrid metric because it will have two types. Maybe with the coordination of a downstream scraper, we could get that to work, but it's definitely not trivial.

2021-09-15 22:37 UTC, r3mariano approved these changes
lgtm! i think moving this to v2 is a good idea

2021-09-16 21:27 UTC, maddiehayes approved these changes
looks good to me, backwards compatible and neat. exposes defaults to users

2021-09-16 21:27 UTC, maddiehayes commented on misk-metrics-testing/src/main/kotlin/misk/metrics/FakeMetricsModule.kt
> +import misk.metrics.v2.FakeMetricsModule as FakeMetricsModuleV2
some unused imports @MatthewDolan

2021-09-17 00:24 UTC, merged