Add getset support to misk-redis
cashapp/misk pull request #2885
Opened 2023-07-24 21:42 UTC by salamagd

Adds support for getting the current value and setting a new value on a single key in an atomic command. Introduces the `getset` and `getsetnx` commands, which can both be used with or without an `expiryDuration`, with the latter only setting the new value if there is a current, non-expired value at the specified key. Behind the scenes, this uses the Redis `SET` command with the `GET` option. `getsetnx` (ie. the use of `SET` with both `GET` and `NX` options) is only supported with Redis version 7.0 and later.

This change also bumps the Docker Redis `alpine` image version used for testing from `6.2` to `7.0`, the current stable version.

2023-07-24 22:19 UTC, adrw approved these changes
LG

2023-07-26 14:20 UTC, keeferrourke requested changes

2023-07-26 14:20 UTC, keeferrourke commented on misk-redis-testing/src/main/kotlin/misk/redis/testing/DockerRedis.kt
> +  private const val redisVersion = "7.0"
We don't support Redis 7 yet!

2023-08-01 16:56 UTC, salamagd commented
Closing for now due to not getting Redis 7 support for a while.

2023-08-01 16:56 UTC, closed without merging